// src/lib/mock-listings.ts
// Placeholder listing data, standing in for Supabase until auth + the
// housing-office feed are wired up (see CLAUDE.md build order, steps 5-6).
// Content matches /design-reference/milhaus-landing-mockup.html so the
// ported page renders identically to the approved design.

import type { Listing } from "@/lib/types";

export const mockListings: Listing[] = [
  {
    id: "boeblingen-hauptstr",
    type: "rental",
    title: "3-bedroom house near Panzer Kaserne",
    description:
      "Bright, recently renovated house a short drive from Panzer Kaserne. Fenced yard, attached garage.",
    address: "Hauptstraße 14",
    city: "Böblingen",
    base: "Stuttgart",
    distanceToBase: "12 min to Panzer Kaserne",
    priceEurMonth: 1180,
    bedrooms: 3,
    bathrooms: 2,
    sizeSqm: 110,
    availableFrom: "2026-09-15",
    photos: [],
    amenities: [],
    source: "housing_office",
    status: "active",
    isFeatured: false,
    ownerId: "mock-housing-office",
    createdAt: "2026-08-01T00:00:00.000Z",
    updatedAt: "2026-08-01T00:00:00.000Z",
    statusChangedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "sindelfingen-gartenweg",
    type: "rental",
    title: "2-bedroom apartment, PCS move-out",
    description:
      "Our family is PCSing in October — clean, well-kept 2-bed apartment close to shopping and the Autobahn on-ramp.",
    address: "Gartenweg 7",
    city: "Sindelfingen",
    base: "Stuttgart",
    distanceToBase: "9 min to Panzer Kaserne",
    priceEurMonth: 950,
    bedrooms: 2,
    bathrooms: 1,
    sizeSqm: 78,
    availableFrom: "2026-10-01",
    photos: [],
    amenities: [],
    source: "self_listed",
    status: "active",
    isFeatured: false,
    ownerId: "mock-family-1",
    createdAt: "2026-08-05T00:00:00.000Z",
    updatedAt: "2026-08-05T00:00:00.000Z",
    statusChangedAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "herrenberg-lindenallee",
    type: "rental",
    title: "4-bedroom family home",
    description:
      "Spacious 4-bedroom home with a large garden, previously rented through the housing office.",
    address: "Lindenallee 22",
    city: "Herrenberg",
    base: "Stuttgart",
    distanceToBase: "18 min to Panzer Kaserne",
    priceEurMonth: 1420,
    bedrooms: 4,
    bathrooms: 2,
    sizeSqm: 142,
    availableFrom: "2026-08-01",
    photos: [],
    amenities: [],
    source: "housing_office",
    status: "rented",
    isFeatured: false,
    ownerId: "mock-housing-office",
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-08-10T00:00:00.000Z",
    statusChangedAt: "2026-08-10T00:00:00.000Z",
  },
  {
    id: "kaiserslautern-bahnhofstr",
    type: "rental",
    title: "3-bedroom townhouse near Ramstein",
    description:
      "Modern townhouse in a quiet neighborhood, easy commute to Ramstein AB. Listed by an outgoing family.",
    address: "Bahnhofstraße 41",
    city: "Kaiserslautern",
    base: "Kaiserslautern",
    distanceToBase: "14 min to Ramstein",
    priceEurMonth: 1050,
    bedrooms: 3,
    bathrooms: 1,
    sizeSqm: 95,
    availableFrom: "2026-09-01",
    photos: [],
    amenities: [],
    source: "self_listed",
    status: "active",
    isFeatured: false,
    ownerId: "mock-family-2",
    createdAt: "2026-08-03T00:00:00.000Z",
    updatedAt: "2026-08-03T00:00:00.000Z",
    statusChangedAt: "2026-08-03T00:00:00.000Z",
  },
  {
    id: "ramstein-miesenbach-schulstr",
    type: "rental",
    title: "3-bedroom house, walk to base",
    description:
      "Housing office listing just minutes from the gate — 3 bed, 2 bath, move-in ready.",
    address: "Schulstraße 5",
    city: "Ramstein-Miesenbach",
    base: "Ramstein",
    distanceToBase: "6 min to base",
    priceEurMonth: 1290,
    bedrooms: 3,
    bathrooms: 2,
    sizeSqm: 118,
    availableFrom: "2026-09-01",
    photos: [],
    amenities: [],
    source: "housing_office",
    status: "active",
    isFeatured: false,
    ownerId: "mock-housing-office",
    createdAt: "2026-08-02T00:00:00.000Z",
    updatedAt: "2026-08-02T00:00:00.000Z",
    statusChangedAt: "2026-08-02T00:00:00.000Z",
  },
  {
    id: "wiesbaden-goethestr",
    type: "rental",
    title: "2-bedroom apartment near Clay Kaserne",
    description:
      "Cozy 2-bedroom apartment close to Clay Kaserne. Outgoing family moving stateside in September.",
    address: "Goethestraße 9",
    city: "Wiesbaden",
    base: "Wiesbaden",
    distanceToBase: "11 min to Clay Kaserne",
    priceEurMonth: 890,
    bedrooms: 2,
    bathrooms: 1,
    sizeSqm: 72,
    availableFrom: "2026-09-20",
    photos: [],
    amenities: [],
    source: "self_listed",
    status: "active",
    isFeatured: false,
    ownerId: "mock-family-3",
    createdAt: "2026-08-07T00:00:00.000Z",
    updatedAt: "2026-08-07T00:00:00.000Z",
    statusChangedAt: "2026-08-07T00:00:00.000Z",
  },
];
